title: Repositório GEOGRÁFICO
logo: /assets/img/logo.png
description: Repositório Geográfico.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: https://www.regrubeis.com/geografia
  tar_url: https://www.regrubeis.com/geografia
  repository_url: https://www.regrubeis.com/geografia
  repository_nwo: https://www.regrubeis.com/geografia
  owner_url: https://www.regrubeis.com/geografia
  owner_name: Regrubeis.com