title: Repositório GEOGRÁFICO
logo: /assets/img/logo.png
description: Repositório Geográfico.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: https://regrubeis.github.io/geografico/
  tar_url: https://regrubeis.github.io/geografico/
  repository_url: https://regrubeis.github.io/geografico/
  repository_nwo: https://regrubeis.github.io/geografico/
  owner_url: https://regrubeis.github.io/geografico/
  owner_name: Regrubeis.com
